//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaladeChat.SRChat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRChat.ServicioChatSoap")]
    public interface ServicioChatSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chatiar", ReplyAction="*")]
        SaladeChat.SRChat.chatiarResponse chatiar(SaladeChat.SRChat.chatiarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chatiar", ReplyAction="*")]
        System.Threading.Tasks.Task<SaladeChat.SRChat.chatiarResponse> chatiarAsync(SaladeChat.SRChat.chatiarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class chatiarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="chatiar", Namespace="http://tempuri.org/", Order=0)]
        public SaladeChat.SRChat.chatiarRequestBody Body;
        
        public chatiarRequest() {
        }
        
        public chatiarRequest(SaladeChat.SRChat.chatiarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class chatiarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensaje;
        
        public chatiarRequestBody() {
        }
        
        public chatiarRequestBody(string Mensaje) {
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class chatiarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="chatiarResponse", Namespace="http://tempuri.org/", Order=0)]
        public SaladeChat.SRChat.chatiarResponseBody Body;
        
        public chatiarResponse() {
        }
        
        public chatiarResponse(SaladeChat.SRChat.chatiarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class chatiarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string chatiarResult;
        
        public chatiarResponseBody() {
        }
        
        public chatiarResponseBody(string chatiarResult) {
            this.chatiarResult = chatiarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioChatSoapChannel : SaladeChat.SRChat.ServicioChatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatSoapClient : System.ServiceModel.ClientBase<SaladeChat.SRChat.ServicioChatSoap>, SaladeChat.SRChat.ServicioChatSoap {
        
        public ServicioChatSoapClient() {
        }
        
        public ServicioChatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioChatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaladeChat.SRChat.chatiarResponse SaladeChat.SRChat.ServicioChatSoap.chatiar(SaladeChat.SRChat.chatiarRequest request) {
            return base.Channel.chatiar(request);
        }
        
        public string chatiar(string Mensaje) {
            SaladeChat.SRChat.chatiarRequest inValue = new SaladeChat.SRChat.chatiarRequest();
            inValue.Body = new SaladeChat.SRChat.chatiarRequestBody();
            inValue.Body.Mensaje = Mensaje;
            SaladeChat.SRChat.chatiarResponse retVal = ((SaladeChat.SRChat.ServicioChatSoap)(this)).chatiar(inValue);
            return retVal.Body.chatiarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaladeChat.SRChat.chatiarResponse> SaladeChat.SRChat.ServicioChatSoap.chatiarAsync(SaladeChat.SRChat.chatiarRequest request) {
            return base.Channel.chatiarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaladeChat.SRChat.chatiarResponse> chatiarAsync(string Mensaje) {
            SaladeChat.SRChat.chatiarRequest inValue = new SaladeChat.SRChat.chatiarRequest();
            inValue.Body = new SaladeChat.SRChat.chatiarRequestBody();
            inValue.Body.Mensaje = Mensaje;
            return ((SaladeChat.SRChat.ServicioChatSoap)(this)).chatiarAsync(inValue);
        }
    }
}
